<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\RayTree.Plugins.Deduplication.Redis\RayTree.Plugins.Deduplication.Redis.csproj" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Update="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
