<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Kafka queue publisher plugin for entity change distribution</Description>
    <PackageTags>kafka;change-tracking;queue</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RayTree.Core\RayTree.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka"/>
  </ItemGroup>
</Project>
