<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>RabbitMQ queue publisher plugin for entity change distribution</Description>
    <PackageTags>rabbitmq;amqp;change-tracking;queue</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RayTree.Core\RayTree.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client"/>
  </ItemGroup>
</Project>
