<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>RabbitMQ queue publisher plugin for entity change distribution</Description>
    <PackageTags>rabbitmq;amqp;change-tracking;queue</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RayTree.Core\RayTree.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
</Project>
