<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>LZ4 compressor plugin for entity change messages using lz4net</Description>
    <PackageTags>lz4;compression;change-tracking</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RayTree.Core\RayTree.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="K4os.Compression.LZ4" />
  </ItemGroup>
</Project>
