using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using RayTree.Core.Models;
using RayTree.Core.Tracking;

namespace RayTree.Plugins.InMemory.Tests;

public class InMemoryOutboxTests
{
    private class TestEntity
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }

    [Test]
    public async Task WriteAsync_StoresChange_WithAutoGeneratedId()
    {
        var outbox = new InMemoryOutbox();
        var change = CreateTestChange();

        await outbox.WriteAsync(change);

        Assert.That(change.Id, Is.GreaterThan(0));
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);
        Assert.That(stored, Is.Not.Null);
        Assert.That(stored!.EntityId, Is.EqualTo(change.EntityId));
    }

    [Test]
    public async Task GetUnpublishedAsync_ReturnsOnlyUnpublishedChanges()
    {
        var outbox = new InMemoryOutbox();
        var change1 = CreateTestChange();
        var change2 = CreateTestChange();

        await outbox.WriteAsync(change1);
        await outbox.WriteAsync(change2);

        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);

        Assert.That(unpublished, Has.Count.EqualTo(2));
    }

    [Test]
    public async Task MarkPublishedAsync_MarksChangeAsPublished()
    {
        var outbox = new InMemoryOutbox();
        var change = CreateTestChange();
        await outbox.WriteAsync(change);

        await outbox.MarkPublishedAsync(change.Id);
        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);

        Assert.That(unpublished, Is.Empty);
    }

    [Test]
    public async Task GetUnpublishedAsync_WithChangeTypeFilter_ReturnsMatchingChanges()
    {
        var outbox = new InMemoryOutbox();
        var change1 = new EntityChange<TestEntity> { EntityType = typeof(TestEntity).FullName!, EntityId = "1", ChangeType = ChangeType.Insert, State = new TestEntity { Id = 1 } };
        var change2 = new EntityChange<TestEntity> { EntityType = typeof(TestEntity).FullName!, EntityId = "2", ChangeType = ChangeType.Delete, State = new TestEntity { Id = 2 } };

        await outbox.WriteAsync(change1);
        await outbox.WriteAsync(change2);

        var filtered = await outbox.GetUnpublishedAsync<TestEntity>(changeType: ChangeType.Insert, batchSize: 10);

        Assert.That(filtered, Has.Count.EqualTo(1));
        Assert.That(filtered[0].ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task CleanupPublishedAsync_RemovesOldPublishedChanges()
    {
        var outbox = new InMemoryOutbox();
        var oldChange = CreateTestChange();
        oldChange.Timestamp = DateTime.UtcNow.AddHours(-2);
        var newChange = CreateTestChange();

        await outbox.WriteAsync(oldChange);
        await outbox.WriteAsync(newChange);
        await outbox.MarkPublishedAsync(oldChange.Id);

        await outbox.CleanupPublishedAsync(TimeSpan.FromHours(1));
        var all = outbox.GetAll();

        Assert.That(all, Has.Count.EqualTo(1));
        Assert.That(all[0].Id, Is.EqualTo(newChange.Id));
    }

    [Test]
    public async Task Clear_RemovesAllChanges()
    {
        var outbox = new InMemoryOutbox();
        await outbox.WriteAsync(CreateTestChange());
        await outbox.WriteAsync(CreateTestChange());

        outbox.Clear();

        Assert.That(outbox.GetAll(), Is.Empty);
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var outbox = new InMemoryOutbox();
        var result = await outbox.GetByIdAsync<TestEntity>(999);
        Assert.That(result, Is.Null);
    }

    private static EntityChange<TestEntity> CreateTestChange() => new()
    {
        EntityType = typeof(TestEntity).FullName!,
        EntityId = Guid.NewGuid().ToString(),
        ChangeType = ChangeType.Insert,
        Timestamp = DateTime.UtcNow,
        State = new TestEntity { Id = 1, Name = "Test" }
    };
}

public class InMemoryRepositoryTests
{
    private class TestEntity
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }

    [Test]
    public async Task InsertAsync_StoresEntity()
    {
        var repo = new InMemoryRepository<TestEntity>();
        var entity = new TestEntity { Id = 1, Name = "Test" };

        await repo.InsertAsync(entity);
        var result = await repo.GetByIdAsync([1]);

        Assert.That(result, Is.Not.Null);
        Assert.That(result!.Name, Is.EqualTo("Test"));
    }

    [Test]
    public async Task UpdateAsync_UpdatesExistingEntity()
    {
        var repo = new InMemoryRepository<TestEntity>();
        var entity = new TestEntity { Id = 1, Name = "Original" };
        await repo.InsertAsync(entity);

        entity.Name = "Updated";
        await repo.UpdateAsync(entity);

        var result = await repo.GetByIdAsync([1]);
        Assert.That(result!.Name, Is.EqualTo("Updated"));
    }

    [Test]
    public async Task DeleteAsync_RemovesEntity()
    {
        var repo = new InMemoryRepository<TestEntity>();
        var entity = new TestEntity { Id = 1, Name = "Test" };
        await repo.InsertAsync(entity);

        await repo.DeleteAsync(entity);
        var result = await repo.GetByIdAsync([1]);

        Assert.That(result, Is.Null);
    }

    [Test]
    public async Task Clear_RemovesAllEntities()
    {
        var repo = new InMemoryRepository<TestEntity>();
        await repo.InsertAsync(new TestEntity { Id = 1 });
        await repo.InsertAsync(new TestEntity { Id = 2 });

        repo.Clear();

        Assert.That(repo.GetAll(), Is.Empty);
    }

    [Test]
    public void GetByIdAsync_WrongKeyValueCount_Throws()
    {
        var repo = new InMemoryRepository<TestEntity>();
        Assert.That(
            async () => await repo.GetByIdAsync([1, 2]),
            Throws.ArgumentException.With.Message.Contains("Expected 1"));
    }
}

public class InMemoryRepositoryCompositeKeyTests
{
    private class CompositeEntity
    {
        [Key, Column(Order = 0)] public string TenantId { get; set; } = string.Empty;
        [Key, Column(Order = 1)] public string UserId { get; set; } = string.Empty;
        public string? Name { get; set; }
    }

    [Test]
    public async Task GetByIdAsync_CompositeKey_DoesNotCollideBetweenAmbiguousValues()
    {
        // With a pipe separator, ("a|b", "c") and ("a", "b|c") both produce the key "a|b|c".
        // With the null-char separator they produce distinct keys, so the two entities must
        // remain independent.
        var repo = new InMemoryRepository<CompositeEntity>();
        var e1 = new CompositeEntity { TenantId = "a|b", UserId = "c", Name = "first" };
        var e2 = new CompositeEntity { TenantId = "a", UserId = "b|c", Name = "second" };

        await repo.InsertAsync(e1);
        await repo.InsertAsync(e2);

        var r1 = await repo.GetByIdAsync(["a|b", "c"]);
        var r2 = await repo.GetByIdAsync(["a", "b|c"]);

        Assert.That(r1, Is.Not.Null);
        Assert.That(r1!.Name, Is.EqualTo("first"));
        Assert.That(r2, Is.Not.Null);
        Assert.That(r2!.Name, Is.EqualTo("second"));
    }
}

public class InMemoryQueueTests
{
    private class TestEntity
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }

    [Test]
    public async Task PublishAsync_MakesMessageAvailableForConsumption()
    {
        var queue = new InMemoryQueue();
        var change = new EntityChange<TestEntity>
        {
            EntityType = "TestEntity",
            EntityId = "1",
            ChangeType = ChangeType.Insert,

        };
        var payloadData = "test payload"u8.ToArray();

        await queue.PublishAsync(new MessageEnvelope
        {
            EntityType = change.EntityType,
            EntityId = change.EntityId,
            ChangeType = change.ChangeType,
            CorrelationId = change.CorrelationId,
            Version = change.Version,
            Timestamp = change.Timestamp,
            Payload = payloadData
        });

        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
        var message = await queue.Reader.ReadAsync(cts.Token);
        Assert.That(message.EntityId, Is.EqualTo("1"));
        Assert.That(message.Payload, Is.EqualTo(payloadData));
    }

    [Test]
    public async Task ConsumeAsync_ReturnsMessagesInOrder()
    {
        var queue = new InMemoryQueue();
        var payloadData1 = Encoding.UTF8.GetBytes("payload1");
        var payloadData2 = Encoding.UTF8.GetBytes("payload2");

        await queue.PublishAsync(new MessageEnvelope { EntityId = "1", Payload = payloadData1 });
        await queue.PublishAsync(new MessageEnvelope { EntityId = "2", Payload = payloadData2 });

        var messages = new List<MessageEnvelope>();
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));

        await foreach (var envelope in queue.ConsumeAsync(cts.Token))
        {
            messages.Add(envelope);
            if (messages.Count == 2) break;
        }

        Assert.That(messages, Has.Count.EqualTo(2));
        Assert.That(messages[0].EntityId, Is.EqualTo("1"));
        Assert.That(messages[1].EntityId, Is.EqualTo("2"));
    }

    [Test]
    public void Complete_StopsConsuming()
    {
        var queue = new InMemoryQueue();
        queue.Complete();
        Assert.That(queue.Reader.Completion.IsCompleted, Is.True);
    }

}
