using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Npgsql;
using RayTree.Core.Models;
using RayTree.Core.Tracking;
using RayTree.Plugins.InMemory;
using RayTree.Plugins.PostgreSQL.Outbox;
using Testcontainers.PostgreSql;

namespace RayTree.Plugins.PostgreSQL.Tests;

public class TestEntity
{
    public int Id { get; set; }
}

[NonParallelizable]
public class PostgreSqlOutboxIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder(image: "postgres:16-alpine")
        .Build();

    private EntityChangeTracker _tracker = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        await _postgres.StartAsync();
    }

    [SetUp]
    public async Task SetUp()
    {
        var builder = new ChangeTrackingBuilder();
        builder.ForEntity<TestEntity>(e => e
            .UseOutbox(new PostgreSqlOutbox<TestEntity>(new()
            {
                ConnectionString = _postgres.GetConnectionString(),
                OutboxTableName = "test_entity_outbox"
            }))
            .UseQueue(new InMemoryQueue())
            .UseSerializer(new RayTree.Plugins.Serializers.Json.JsonSerializerPlugin())
            .UseCompressor(new RayTree.Plugins.Compressors.Gzip.GzipCompressorPlugin()));

        _tracker = builder.Build();
    }

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [TearDown]
    public async Task TearDown()
    {
        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("TRUNCATE test_entity_outbox RESTART IDENTITY", conn);
        await cmd.ExecuteNonQueryAsync();
    }

    [Test]
    public async Task WriteAsync_InsertsChange_WithAutoGeneratedId()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = CreateTestChange();

        await outbox!.WriteAsync(change);

        Assert.That(change.Id, Is.GreaterThan(0));
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);
        Assert.That(stored, Is.Not.Null);
        Assert.That(stored!.EntityId, Is.EqualTo(change.EntityId));
        Assert.That(stored.ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_ReturnsUnpublishedChanges()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange());
        await outbox.WriteAsync(CreateTestChange());

        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);
        Assert.That(unpublished, Has.Count.EqualTo(2));
    }

    [Test]
    public async Task MarkPublishedAsync_MarksChangeAsPublished()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = CreateTestChange();

        await outbox!.WriteAsync(change);
        await outbox.MarkPublishedAsync(change.Id);

        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);
        Assert.That(unpublished, Is.Empty);
    }

    [Test]
    public async Task GetUnpublishedAsync_WithChangeTypeFilter_ReturnsMatchingChanges()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange(changeType: ChangeType.Insert));
        await outbox.WriteAsync(CreateTestChange(changeType: ChangeType.Delete));

        var filtered = await outbox.GetUnpublishedAsync<TestEntity>(changeType: ChangeType.Insert, batchSize: 10);
        Assert.That(filtered, Has.Count.EqualTo(1));
        Assert.That(filtered[0].ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_WithSinceFilter_ReturnsMatchingChanges()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-2)));
        await outbox.WriteAsync(CreateTestChange(timestamp: DateTime.UtcNow));

        var filtered = await outbox.GetUnpublishedAsync<TestEntity>(since: DateTime.UtcNow.AddMinutes(-30), batchSize: 10);
        Assert.That(filtered, Has.Count.EqualTo(1));
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var result = await outbox!.GetByIdAsync<TestEntity>(999);
        Assert.That(result, Is.Null);
    }

    [Test]
    public async Task CleanupPublishedAsync_RemovesOldPublishedChanges()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        var oldChange = CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-3));
        var newChange = CreateTestChange(timestamp: DateTime.UtcNow);

        await outbox!.WriteAsync(oldChange);
        await outbox.WriteAsync(newChange);
        await outbox.MarkPublishedAsync(oldChange.Id);

        var deleted = await outbox.CleanupPublishedAsync(TimeSpan.FromHours(1));
        Assert.That(deleted, Is.EqualTo(1));
    }

    [Test]
    public async Task WriteAsync_StoresCorrelationId()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var correlationId = Guid.NewGuid();
        var change = CreateTestChange();
        change.CorrelationId = correlationId;

        await outbox!.WriteAsync(change);
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);
        Assert.That(stored!.CorrelationId, Is.EqualTo(correlationId));
    }

    [Test]
    public async Task WriteAsync_WithState_RoundTripsEntityData()
    {
        var outbox = _tracker.Publisher.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = new EntityChange<TestEntity>
        {
            EntityType = typeof(TestEntity).FullName!,
            EntityId = "42",
            ChangeType = ChangeType.Insert,
            State = new TestEntity { Id = 42 }
        };

        await outbox!.WriteAsync(change);
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);

        Assert.That(stored!.State, Is.Not.Null);
        Assert.That(stored.State!.Id, Is.EqualTo(42));
    }

    private static EntityChange<TestEntity> CreateTestChange(
        ChangeType changeType = ChangeType.Insert,
        DateTime? timestamp = null) => new()
    {
        EntityType = typeof(TestEntity).FullName!,
        EntityId = Guid.NewGuid().ToString(),
        ChangeType = changeType,
        Timestamp = timestamp ?? DateTime.UtcNow,
        CorrelationId = Guid.NewGuid(),
        State = new TestEntity { Id = 1 }
    };
}

[Table("test_users")]
public class TestUser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("email")]
    public string? Email { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }
}

[Table("annotated_entity")]
public class AnnotatedEntity
{
    [Column("custom_id")]
    public int Id { get; set; }

    [Column("full_name")]
    public string? Name { get; set; }

    [NotMapped]
    public string? Ignored { get; set; }

    [Required]
    public string RequiredField { get; set; } = string.Empty;

    [Required]
    public int? RequiredNullableInt { get; set; }

    [MaxLength(200)]
    public string? Bio { get; set; }

    [StringLength(50)]
    public string? Code { get; set; }

    [MaxLength(100)]
    [StringLength(20)]
    public string? BothLengths { get; set; }

    [Column(TypeName = "JSONB")]
    public string? Metadata { get; set; }
}

public class KeyAnnotatedEntity
{
    [Key]
    public int OrderId { get; set; }

    public string? Description { get; set; }
}

public class CompositeKeyEntity
{
    [Key, Column(Order = 0)]
    public int OrderId { get; set; }

    [Key, Column(Order = 1)]
    public int LineNumber { get; set; }

    public string? Product { get; set; }
}

public class NoKeyEntity
{
    public string? Name { get; set; }
}
