using System.ComponentModel.DataAnnotations.Schema;
using Npgsql;
using RayTree.Models;
using RayTree.Plugins;
using RayTree.Plugins.InMemory;
using RayTree.Plugins.PostgreSQL;
using RayTree.Tracking;
using Testcontainers.PostgreSql;

namespace RayTree.Plugins.PostgreSQL.Tests;

public class TestEntity
{
    public int Id { get; set; }
}

[NonParallelizable]
public class PostgreSqlOutboxIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    private EntityChangeTracker _tracker = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        await _postgres.StartAsync();
    }

    [SetUp]
    public async Task SetUp()
    {
        var builder = new ChangeTrackingBuilder();
        builder.ForEntity<TestEntity>()
            .UseOutbox(new PostgreSqlOutbox<TestEntity>(new()
            {
                ConnectionString = _postgres.GetConnectionString(),
                OutboxTableName = "test_entity_outbox"
            }))
            .UseQueue(new InMemoryQueue())
            .UseSerializer(new RayTree.Plugins.Serializers.Json.JsonSerializerPlugin())
            .UseCompressor(new RayTree.Plugins.Compressors.Gzip.GzipCompressorPlugin());

        _tracker = builder.Build();
    }

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [TearDown]
    public async Task TearDown()
    {
        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("TRUNCATE test_entity_outbox RESTART IDENTITY", conn);
        await cmd.ExecuteNonQueryAsync();
    }

    [Test]
    public async Task WriteAsync_InsertsChange_WithAutoGeneratedId()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = CreateTestChange();

        await outbox!.WriteAsync(change);

        Assert.That(change.Id, Is.GreaterThan(0));
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);
        Assert.That(stored, Is.Not.Null);
        Assert.That(stored!.EntityId, Is.EqualTo(change.EntityId));
        Assert.That(stored.ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_ReturnsUnpublishedChanges()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange());
        await outbox.WriteAsync(CreateTestChange());

        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);
        Assert.That(unpublished, Has.Count.EqualTo(2));
    }

    [Test]
    public async Task MarkPublishedAsync_MarksChangeAsPublished()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = CreateTestChange();

        await outbox!.WriteAsync(change);
        await outbox.MarkPublishedAsync(change.Id);

        var unpublished = await outbox.GetUnpublishedAsync<TestEntity>(10);
        Assert.That(unpublished, Is.Empty);
    }

    [Test]
    public async Task GetUnpublishedAsync_WithChangeTypeFilter_ReturnsMatchingChanges()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange(changeType: ChangeType.Insert));
        await outbox.WriteAsync(CreateTestChange(changeType: ChangeType.Delete));

        var filtered = await outbox.GetUnpublishedAsync<TestEntity>(changeType: ChangeType.Insert, batchSize: 10);
        Assert.That(filtered, Has.Count.EqualTo(1));
        Assert.That(filtered[0].ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_WithSinceFilter_ReturnsMatchingChanges()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        await outbox!.WriteAsync(CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-2)));
        await outbox.WriteAsync(CreateTestChange(timestamp: DateTime.UtcNow));

        var filtered = await outbox.GetUnpublishedAsync<TestEntity>(since: DateTime.UtcNow.AddMinutes(-30), batchSize: 10);
        Assert.That(filtered, Has.Count.EqualTo(1));
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var result = await outbox!.GetByIdAsync<TestEntity>(999);
        Assert.That(result, Is.Null);
    }

    [Test]
    public async Task CleanupPublishedAsync_RemovesOldPublishedChanges()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;

        var oldChange = CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-3));
        var newChange = CreateTestChange(timestamp: DateTime.UtcNow);

        await outbox!.WriteAsync(oldChange);
        await outbox.WriteAsync(newChange);
        await outbox.MarkPublishedAsync(oldChange.Id);

        var deleted = await outbox.CleanupPublishedAsync(TimeSpan.FromHours(1));
        Assert.That(deleted, Is.EqualTo(1));
    }

    [Test]
    public async Task WriteAsync_StoresCorrelationId()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var correlationId = Guid.NewGuid();
        var change = CreateTestChange();
        change.CorrelationId = correlationId;

        await outbox!.WriteAsync(change);
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);
        Assert.That(stored!.CorrelationId, Is.EqualTo(correlationId));
    }

    [Test]
    public async Task WriteAsync_WithState_RoundTripsEntityData()
    {
        var outbox = _tracker.GetOutbox(typeof(TestEntity)) as PostgreSqlOutbox<TestEntity>;
        var change = new EntityChange<TestEntity>
        {
            EntityType = typeof(TestEntity).FullName!,
            EntityId = "42",
            ChangeType = ChangeType.Insert,
            State = new TestEntity { Id = 42 }
        };

        await outbox!.WriteAsync(change);
        var stored = await outbox.GetByIdAsync<TestEntity>(change.Id);

        Assert.That(stored!.State, Is.Not.Null);
        Assert.That(stored.State!.Id, Is.EqualTo(42));
    }

    private static EntityChange<TestEntity> CreateTestChange(
        ChangeType changeType = ChangeType.Insert,
        DateTime? timestamp = null) => new()
    {
        EntityType = typeof(TestEntity).FullName!,
        EntityId = Guid.NewGuid().ToString(),
        ChangeType = changeType,
        Timestamp = timestamp ?? DateTime.UtcNow,
        CorrelationId = Guid.NewGuid(),
        State = new TestEntity { Id = 1 }
    };
}

[NonParallelizable]
public class PostgreSqlRepositoryIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    private EntityChangeTracker _tracker = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        await _postgres.StartAsync();
    }

    [SetUp]
    public async Task SetUp()
    {
        var builder = new ChangeTrackingBuilder();
        builder.ForEntity<TestUser>()
            .UseRepository(new PostgreSqlRepository<TestUser>(new()
            {
                ConnectionString = _postgres.GetConnectionString(),
                TableName = "test_users"
            }))
            .UseOutbox(new PostgreSqlOutbox<TestUser>(new()
            {
                ConnectionString = _postgres.GetConnectionString(),
                OutboxTableName = "test_users_outbox"
            }))
            .UseQueue(new InMemoryQueue())
            .UseSerializer(new RayTree.Plugins.Serializers.Json.JsonSerializerPlugin())
            .UseCompressor(new RayTree.Plugins.Compressors.Gzip.GzipCompressorPlugin());

        _tracker = builder.Build();
    }

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [Test]
    public async Task InsertAsync_StoresEntity()
    {
        var repo = _tracker.GetRepository(typeof(TestUser)) as PostgreSqlRepository<TestUser>;
        var user = new TestUser();

        await repo!.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        Assert.That(userId, Is.GreaterThan(0));
        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Not.Null);
    }

    [Test]
    public async Task UpdateAsync_UpdatesTimestamp()
    {
        var repo = _tracker.GetRepository(typeof(TestUser)) as PostgreSqlRepository<TestUser>;
        var user = new TestUser();
        await repo!.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        var beforeUpdate = await repo.GetByIdAsync(userId);
        Assert.That(beforeUpdate, Is.Not.Null);

        await repo.UpdateAsync(new TestUser { Id = userId });
        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Not.Null);
    }

    [Test]
    public async Task DeleteAsync_RemovesEntity()
    {
        var repo = _tracker.GetRepository(typeof(TestUser)) as PostgreSqlRepository<TestUser>;
        var user = new TestUser();
        await repo!.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        await repo.DeleteAsync(new TestUser { Id = userId });

        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Null);
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var repo = _tracker.GetRepository(typeof(TestUser)) as PostgreSqlRepository<TestUser>;
        var result = await repo!.GetByIdAsync(999);
        Assert.That(result, Is.Null);
    }

    private async Task<int> GetLatestUserIdAsync()
    {
        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("SELECT id FROM test_users ORDER BY id DESC LIMIT 1", conn);
        var result = await cmd.ExecuteScalarAsync();
        return Convert.ToInt32(result!);
    }

    [TearDown]
    public async Task TearDown()
    {
        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("TRUNCATE test_users, test_users_outbox RESTART IDENTITY", conn);
        await cmd.ExecuteNonQueryAsync();
    }
}

public class DefaultSourceTableNameTests
{
    [Test]
    public void Constructor_WithNoTableName_DerivesSnakeCaseFromEntityType()
    {
        var options = new PostgreSqlRepositoryOptions { ConnectionString = "Host=localhost" };
        _ = new PostgreSqlRepository<TestEntity>(options);
        Assert.That(options.TableName, Is.EqualTo("test_entity"));
    }

    [Test]
    public void Constructor_WithExplicitTableName_KeepsIt()
    {
        var options = new PostgreSqlRepositoryOptions
        {
            ConnectionString = "Host=localhost",
            TableName = "my_custom_table"
        };
        _ = new PostgreSqlRepository<TestEntity>(options);
        Assert.That(options.TableName, Is.EqualTo("my_custom_table"));
    }
}

[NonParallelizable]
public class DefaultSourceTableNameIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    [OneTimeSetUp]
    public Task OneTimeSetUp() => _postgres.StartAsync();

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [Test]
    public async Task InitializeAsync_WithNoTableName_CreatesTableWithDerivedName()
    {
        var repo = new PostgreSqlRepository<TestEntity>(new PostgreSqlRepositoryOptions
        {
            ConnectionString = _postgres.GetConnectionString()
            // TableName intentionally omitted
        });

        await repo.InitializeAsync();

        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("""
            SELECT COUNT(*) FROM information_schema.tables
            WHERE table_name = 'test_entity'
            """, conn);
        var count = Convert.ToInt32(await cmd.ExecuteScalarAsync());
        Assert.That(count, Is.EqualTo(1));
    }
}

public class DefaultTableNameTests
{
    [Test]
    public void Constructor_WithNoTableName_DerivesSnakeCasePlusOutbox()
    {
        var options = new PostgreSqlOutboxOptions { ConnectionString = "Host=localhost" };
        _ = new PostgreSqlOutbox<TestEntity>(options);
        Assert.That(options.OutboxTableName, Is.EqualTo("test_entity_outbox"));
    }

    [Test]
    public void Constructor_WithExplicitTableName_KeepsIt()
    {
        var options = new PostgreSqlOutboxOptions
        {
            ConnectionString = "Host=localhost",
            OutboxTableName = "my_custom_table"
        };
        _ = new PostgreSqlOutbox<TestEntity>(options);
        Assert.That(options.OutboxTableName, Is.EqualTo("my_custom_table"));
    }
}

[NonParallelizable]
public class DefaultTableNameIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    [OneTimeSetUp]
    public Task OneTimeSetUp() => _postgres.StartAsync();

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [Test]
    public async Task InitializeAsync_WithNoTableName_CreatesTableWithDerivedName()
    {
        var outbox = new PostgreSqlOutbox<TestEntity>(new PostgreSqlOutboxOptions
        {
            ConnectionString = _postgres.GetConnectionString()
            // OutboxTableName intentionally omitted
        });

        await outbox.InitializeAsync();

        await using var conn = new NpgsqlConnection(_postgres.GetConnectionString());
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("""
            SELECT COUNT(*) FROM information_schema.tables
            WHERE table_name = 'test_entity_outbox'
            """, conn);
        var count = Convert.ToInt32(await cmd.ExecuteScalarAsync());
        Assert.That(count, Is.EqualTo(1));
    }
}

[Table("test_users")]
public class TestUser
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("email")]
    public string? Email { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }
}
