using System.ComponentModel.DataAnnotations.Schema;
using Npgsql;
using RayTree.Models;
using RayTree.Tracking;
using Testcontainers.PostgreSql;

namespace RayTree.Plugins.PostgreSQL.Tests;

[NonParallelizable]
public class PostgreSqlOutboxIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    private string _connectionString = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        await _postgres.StartAsync();
        _connectionString = _postgres.GetConnectionString();
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand("""
            CREATE TABLE test_entity_outbox (
                id BIGSERIAL PRIMARY KEY,
                entity_id TEXT NOT NULL,
                change_type TEXT NOT NULL,
                timestamp TIMESTAMPTZ NOT NULL,
                version INT NOT NULL DEFAULT 0,
                correlation_id UUID NOT NULL,
                entity_type TEXT NOT NULL,
                data BYTEA,
                published BOOLEAN NOT NULL DEFAULT FALSE
            );
            """, conn);
        await cmd.ExecuteNonQueryAsync();
    }

    [SetUp]
    public async Task SetUp()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("TRUNCATE test_entity_outbox RESTART IDENTITY", conn);
        await cmd.ExecuteNonQueryAsync();
    }

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [Test]
    public async Task WriteAsync_InsertsChange_WithAutoGeneratedId()
    {
        var outbox = CreateOutbox();
        var change = CreateTestChange();

        await outbox.WriteAsync(change);

        Assert.That(change.Id, Is.GreaterThan(0));
        var stored = await outbox.GetByIdAsync(change.Id);
        Assert.That(stored, Is.Not.Null);
        Assert.That(stored!.EntityId, Is.EqualTo(change.EntityId));
        Assert.That(stored.ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_ReturnsUnpublishedChanges()
    {
        var outbox = CreateOutbox();
        var change1 = CreateTestChange();
        var change2 = CreateTestChange();

        await outbox.WriteAsync(change1);
        await outbox.WriteAsync(change2);

        var unpublished = await outbox.GetUnpublishedAsync(10);

        Assert.That(unpublished, Has.Count.EqualTo(2));
    }

    [Test]
    public async Task MarkPublishedAsync_MarksChangeAsPublished()
    {
        var outbox = CreateOutbox();
        var change = CreateTestChange();
        await outbox.WriteAsync(change);

        await outbox.MarkPublishedAsync(change.Id);

        var unpublished = await outbox.GetUnpublishedAsync(10);
        Assert.That(unpublished, Is.Empty);
    }

    [Test]
    public async Task GetUnpublishedAsync_WithEntityTypeFilter_ReturnsMatchingChanges()
    {
        var outbox = CreateOutbox();
        var changeA = CreateTestChange(entityType: "EntityA");
        var changeB = CreateTestChange(entityType: "EntityB");

        await outbox.WriteAsync(changeA);
        await outbox.WriteAsync(changeB);

        var filtered = await outbox.GetUnpublishedAsync("EntityA", batchSize: 10);

        Assert.That(filtered, Has.Count.EqualTo(1));
        Assert.That(filtered[0].EntityType, Is.EqualTo("EntityA"));
    }

    [Test]
    public async Task GetUnpublishedAsync_WithChangeTypeFilter_ReturnsMatchingChanges()
    {
        var outbox = CreateOutbox();
        var insertChange = CreateTestChange(changeType: ChangeType.Insert);
        var deleteChange = CreateTestChange(changeType: ChangeType.Delete);

        await outbox.WriteAsync(insertChange);
        await outbox.WriteAsync(deleteChange);

        var filtered = await outbox.GetUnpublishedAsync("TestEntity", changeType: ChangeType.Insert, batchSize: 10);

        Assert.That(filtered, Has.Count.EqualTo(1));
        Assert.That(filtered[0].ChangeType, Is.EqualTo(ChangeType.Insert));
    }

    [Test]
    public async Task GetUnpublishedAsync_WithSinceFilter_ReturnsMatchingChanges()
    {
        var outbox = CreateOutbox();
        var oldChange = CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-2));
        var newChange = CreateTestChange(timestamp: DateTime.UtcNow);

        await outbox.WriteAsync(oldChange);
        await outbox.WriteAsync(newChange);

        var filtered = await outbox.GetUnpublishedAsync(
            "TestEntity",
            since: DateTime.UtcNow.AddMinutes(-30),
            batchSize: 10);

        Assert.That(filtered, Has.Count.EqualTo(1));
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var outbox = CreateOutbox();
        var result = await outbox.GetByIdAsync(999);
        Assert.That(result, Is.Null);
    }

    [Test]
    public async Task CleanupPublishedAsync_RemovesOldPublishedChanges()
    {
        var outbox = CreateOutbox();
        var oldChange = CreateTestChange(timestamp: DateTime.UtcNow.AddHours(-3));
        var newChange = CreateTestChange(timestamp: DateTime.UtcNow);

        await outbox.WriteAsync(oldChange);
        await outbox.WriteAsync(newChange);
        await outbox.MarkPublishedAsync(oldChange.Id);

        var deleted = await outbox.CleanupPublishedAsync(TimeSpan.FromHours(1));

        Assert.That(deleted, Is.EqualTo(1));
    }

    [Test]
    public async Task WriteAsync_StoresCorrelationId()
    {
        var outbox = CreateOutbox();
        var correlationId = Guid.NewGuid();
        var change = CreateTestChange();
        change.CorrelationId = correlationId;

        await outbox.WriteAsync(change);

        var stored = await outbox.GetByIdAsync(change.Id);
        Assert.That(stored!.CorrelationId, Is.EqualTo(correlationId));
    }

    private PostgreSqlOutbox CreateOutbox()
    {
        return new PostgreSqlOutbox(new PostgreSqlOutboxOptions
        {
            ConnectionString = _connectionString,
            OutboxTableName = "test_entity_outbox"
        });
    }

    private static EntityChange CreateTestChange(
        string entityType = "TestEntity",
        ChangeType changeType = ChangeType.Insert,
        DateTime? timestamp = null)
    {
        return new EntityChange
        {
            EntityType = entityType,
            EntityId = Guid.NewGuid().ToString(),
            ChangeType = changeType,
            Timestamp = timestamp ?? DateTime.UtcNow,
            CorrelationId = Guid.NewGuid()
        };
    }
}

[NonParallelizable]
public class PostgreSqlRepositoryIntegrationTests : IAsyncDisposable
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .Build();

    private string _connectionString = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        await _postgres.StartAsync();
        _connectionString = _postgres.GetConnectionString();
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand("""
            CREATE TABLE test_users (
                id SERIAL PRIMARY KEY,
                name TEXT NOT NULL DEFAULT 'unknown',
                email TEXT DEFAULT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ
            );
            """, conn);
        await cmd.ExecuteNonQueryAsync();
    }

    [SetUp]
    public async Task SetUp()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand("TRUNCATE test_users RESTART IDENTITY", conn);
        await cmd.ExecuteNonQueryAsync();
    }

    public ValueTask DisposeAsync() => _postgres.DisposeAsync();

    [Test]
    public async Task InsertAsync_StoresEntity()
    {
        var repo = CreateRepository();
        var user = new TestUser();

        await repo.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        Assert.That(userId, Is.GreaterThan(0));
        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Not.Null);
    }

    [Test]
    public async Task UpdateAsync_UpdatesTimestamp()
    {
        var repo = CreateRepository();
        var user = new TestUser();
        await repo.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        var beforeUpdate = await repo.GetByIdAsync(userId);
        Assert.That(beforeUpdate, Is.Not.Null);

        await repo.UpdateAsync(new TestUser { Id = userId });

        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Not.Null);
    }

    [Test]
    public async Task DeleteAsync_RemovesEntity()
    {
        var repo = CreateRepository();
        var user = new TestUser();
        await repo.InsertAsync(user);

        var userId = await GetLatestUserIdAsync();
        await repo.DeleteAsync(new TestUser { Id = userId });

        var stored = await repo.GetByIdAsync(userId);
        Assert.That(stored, Is.Null);
    }

    [Test]
    public async Task GetByIdAsync_WithNonExistentId_ReturnsNull()
    {
        var repo = CreateRepository();
        var result = await repo.GetByIdAsync(999);
        Assert.That(result, Is.Null);
    }

    private PostgreSqlRepository<TestUser> CreateRepository()
    {
        return new PostgreSqlRepository<TestUser>(new PostgreSqlRepositoryOptions
        {
            ConnectionString = _connectionString,
            TableName = "test_users"
        });
    }

    private async Task<int> GetLatestUserIdAsync()
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        using var cmd = new NpgsqlCommand("SELECT id FROM test_users ORDER BY id DESC LIMIT 1", conn);
        var result = await cmd.ExecuteScalarAsync();
        return Convert.ToInt32(result!);
    }
}

[Table("test_users")]
public class TestUser
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("email")]
    public string? Email { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }
}
