<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\RayTree.Plugins.InMemory\RayTree.Plugins.InMemory.csproj" />
    <ProjectReference Include="..\..\src\RayTree.Plugins.Kafka\RayTree.Plugins.Kafka.csproj" />
    <ProjectReference Include="..\..\src\RayTree.Plugins.Serializers.Json\RayTree.Plugins.Serializers.Json.csproj" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.Kafka" />
  </ItemGroup>
</Project>
